linters:
  enable-all: true
  disable:
    - tenv # deprecated
    - depguard
    - dogsled
    - gci
    - godot
    - nolintlint

run:
  timeout: 5m
  allow-parallel-runners: true

issues:
  exclude-use-default: false
  exclude-rules:
    - path: _test\.go
      linters:
        - containedctx
        - funlen
        - gosec
        - wrapcheck
    - path: test/
      linters:
        - containedctx
        - funlen
        - gosec
        - wrapcheck

linters-settings:
  cyclop:
    max-complexity: 15
  exhaustruct:
    include:
      - 'github\.com/nekko-lab/sidauth.+'
  lll:
    line-length: 150
  revive:
    rules:
      - name: package-comments
        disabled: true
  stylecheck:
    checks:
      - all
      - -ST1000
  varnamelen:
    ignore-names:
      - tt
      - tx
      - id
      - db
      - to
      - i
