# This rule is not used by the project sidauth itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over nekko-lab.dev.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: sidauth
    app.kubernetes.io/managed-by: kustomize
  name: authservice-admin-role
rules:
- apiGroups:
  - nekko-lab.dev
  resources:
  - authservices
  verbs:
  - '*'
- apiGroups:
  - nekko-lab.dev
  resources:
  - authservices/status
  verbs:
  - get
