---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - nekko-lab.dev
  resources:
  - authservices
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - nekko-lab.dev
  resources:
  - authservices/finalizers
  verbs:
  - update
- apiGroups:
  - nekko-lab.dev
  resources:
  - authservices/status
  verbs:
  - get
  - patch
  - update
